name: SwiftLint

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read

jobs:
  swiftlint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@692231e42914ac5ddfe5ee44f1c541b1c4a1e9fa0edc028f5d2 # v4.1.6

      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict
        env:
          DIFF_BASE: ${{ github.base_ref }}
